DROP DATABASE IF EXISTS todoList;

CREATE DATABASE IF NOT EXISTS todoList;
USE todoList;

DROP TABLE IF EXISTS `Account`;
CREATE TABLE IF NOT EXISTS `Account`(
	AccountID 			TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	FullName 			NVARCHAR(100) NOT NULL,
	UserName 			VARCHAR(100) UNIQUE KEY NOT NULL,
    Email 				VARCHAR(50) NOT NULL UNIQUE KEY
);

DROP TABLE IF EXISTS `Task`;
CREATE TABLE IF NOT EXISTS `Task`(
	TaskID				INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    Title				NVARCHAR(100) NOT NULL,
    `Status`			NVARCHAR(10) NOT NULL,
    Content				NVARCHAR(1000) NOT NULL,
    Creator				TINYINT UNSIGNED NOT NULL ,
    
     FOREIGN KEY(Creator)REFERENCES `Account`(AccountID)
);

